services:
  atcoder:
    build: .
    volumes:
      - .:/workspace
      - .acc-config:/root/.config/atcoder-cli-nodejs/cpp
      - venv:/workspace/.venv
    tty: true
    stdin_open: true
volumes:
  venv: